{{- if .Values.brAgent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-data-distributed-coordinator-ed.agentName" . }}
  annotations:
{{ include "eric-data-distributed-coordinator-ed.annotations" . | indent 4 }}
  labels:
    chart: {{ template "eric-data-distributed-coordinator-ed.chart" . }}
      {{- include "eric-data-distributed-coordinator-ed.agent.labels" . | indent 4 }}
data:
  application.properties: |
    orchestrator.host={{ include "eric-data-distributed-coordinator-ed.agent.broServiceName" . }}
    orchestrator.port={{ include "eric-data-distributed-coordinator-ed.agent.broGrpcServicePort" . }}
{{- if .Values.brAgent.brLabelValue }}
    dced.agent.id={{ .Values.brAgent.brLabelValue }}
{{ else }}
    dced.agent.id=dc-etcd
{{- end }}
    dced.agent.apiVersion=3.0.1
    dced.agent.fragment.backup.data.path={{.Values.brAgent.backupFileName}}
    dced.endpoint.url={{ template "eric-data-distributed-coordinator-ed.agent.endpoint" . }}
    {{- if .Values.brAgent.backupTypeList }}
    dced.agent.scope={{- template "eric-data-distributed-coordinator-ed.agent.backupTypes" . }}
    {{- end }}
    dced.read.timeout.secs=10
{{- if .Values.brAgent.maxInboundMessageSize }}
    dced.agent.max.inbound.message.size={{.Values.brAgent.maxInboundMessageSize}}
{{ else }}
    dced.agent.max.inbound.message.size=262144000
{{- end }}
{{ .Values.brAgent.properties.applicationProperties | indent 4 }}
{{- if .Values.security.etcd.certificates.enabled }}
    dced.ca.file={{ printf "%s/%s/%s" .Values.security.etcd.certificates.ca.parentDir .Values.security.etcd.certificates.ca.sipTls.path .Values.security.etcd.certificates.ca.sipTls.fileName }}
    dced.client.cert.file={{ printf "%s/clicert.pem" .Values.security.etcd.certificates.client.path }}
    dced.client.cert.keyfile={{ printf "%s/cliprivkey.pem" .Values.security.etcd.certificates.client.path }}
    dced.certificates.enabled=true
{{ else }}
    dced.certificates.enabled=false
{{- end }}
    dced.agent.bro.flag.grpc.siptls.security.enabled={{ .Values.security.tls.agentToBro.enabled }}
  {{- if .Values.security.tls.agentToBro.enabled }}
    dced.agent.bro.siptls.ca.path=/run/sec/cas/siptlsca/cacertbundle.pem
    dced.agent.bro.siptls.ca.name={{ include "eric-data-distributed-coordinator-ed.agent.broServiceName" . }}
  {{- else }}
    dced.agent.bro.siptls.ca.path=""
    dced.agent.bro.siptls.ca.name=""
  {{- end }}
    dced.agent.softwareVersion.description=The Backup and Restore Agent for Distributed Coordinator ED
    dced.agent.softwareVersion.productionDate=date
    dced.agent.softwareVersion.productName=distributed-coordinator-ed-brAgent
    dced.agent.softwareVersion.productNumber=CXC 201 2039/1
    dced.agent.softwareVersion.type=Database
    dced.agent.softwareVersion.revision=2
    dced.agent.download.location=/sharedData/backupdata/
    logging.config=log4j2.xml
    spring.main.banner-mode=off

  log4j2.xml: |
{{ .Values.brAgent.logging.log4jxml | indent 4 }}
{{ end }}
