apiVersion: v1
kind: Service
metadata:
  name: {{ template "eric-data-distributed-coordinator-ed.name" . }}
  labels:
{{- include "eric-data-distributed-coordinator-ed.labels" . | indent 2 }}
  annotations:
{{- include "eric-data-distributed-coordinator-ed.annotations" . | indent 2 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.ports.etcd.client }}
    name: client-port
  selector:
{{- include "eric-data-distributed-coordinator-ed.selectorLabels" . | indent 2 }}
