apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-data-distributed-coordinator-ed.name" . }}-sa
  labels:
    {{- include "eric-data-distributed-coordinator-ed.labels" . | indent 2 }}
automountServiceAccountToken: false