apiVersion: v1
kind: Service
metadata:
  name: {{ template "eric-data-coordinator-zk.fullname" . }}
  labels:
{{- include "eric-data-coordinator-zk.labels" . | indent 4 }}
  annotations:
{{- include "eric-data-coordinator-zk.productinfo" . | indent 4 }}
spec:
  ports:
{{- if or (and ( .Values.global.security.tls.enabled ) ( eq .Values.service.endpoints.datacoordinatorzk.tls.enforced "optional" )) (  eq .Values.global.security.tls.enabled false )  }}
  - port: {{ .Values.clientPort }}
    name: client
{{- end }}
  - port: {{ .Values.network.datacoordinatorzk.adminServer.port }}
    name: admin-server
{{- if  .Values.global.security.tls.enabled }}
  - port: {{ .Values.network.datacoordinatorzk.client.tlsPort }}
    name: client-tls
{{- end }}
  - port: {{ .Values.service.endpoints.datacoordinatorzk.metricsPort  }}
    name: metrics
  selector:
{{- include "eric-data-coordinator-zk.selectorLabels" . | indent 4 }}
