apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-data-coordinator-zk.fullname" . }}-sa
  labels:
{{- include "eric-data-coordinator-zk.labels" . | indent 4 }}
automountServiceAccountToken: false