apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ template "eric-sec-sip-tls.name" . }}-service-account"
  labels:
    {{- include "eric-sec-sip-tls.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-sec-sip-tls.product-info" . | nindent 4 }}

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ template "eric-sec-sip-tls.name" . }}-role"
  labels:
    {{- include "eric-sec-sip-tls.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-sec-sip-tls.product-info" . | nindent 4 }}
rules:
  - apiGroups: ["com.ericsson.sec.tls"]
    resources: ["servercertificates", "clientcertificates", "certificateauthorities"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["siptls.sec.ericsson.com"]
    resources: ["internalcertificates", "internalusercas"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "delete", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ template "eric-sec-sip-tls.name" . }}-rolebinding"
  labels:
    {{- include "eric-sec-sip-tls.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-sec-sip-tls.product-info" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ template "eric-sec-sip-tls.name" . }}-role"
subjects:
- kind: ServiceAccount
  name: "{{ template "eric-sec-sip-tls.name" . }}-service-account"
