# Service account that can be used to fetch credentials from vault

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-sec-key-management.name" . }}-admin
  labels:
    {{- include "eric-sec-key-management.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-sec-key-management.product-info" . | nindent 4 }}
