{{- if and ( .Values.global.security.tls.enabled ) ( eq .Values.security.tls.messagebuskf.provider "sip-tls" ) }}
apiVersion: siptls.sec.ericsson.com/v1alpha1
kind: InternalUserCA
metadata:
  name: {{ template "eric-data-message-bus-kf.fullname" . }}-client-ca
  labels:
{{- include "eric-data-message-bus-kf.labels" . | indent 4 }}
  annotations:
{{- include "eric-data-message-bus-kf.productinfo" . | indent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ template "eric-data-message-bus-kf.client.ca.secret" . }}
    certificateName: clientcacertbundle.pem
  certificate:
    subject:
      cn: {{ template "eric-data-message-bus-kf.fullname" . }}-client-ca
{{- end -}}
