apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-data-message-bus-kf.fullname" . }}-sa
  labels:
{{- include "eric-data-message-bus-kf.labels" . | indent 4 }}
automountServiceAccountToken: false